version: '3.8'
services:
  junsik-mysql:
    container_name: junsik-mysql8
    image: mysql/mysql-server:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--lower_case_table_names=1" ]
    ports:
      - "33306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
